[workspace]
exclude = ["contracts/apps/croncat", "contracts/apps/dca"]
members = ["contracts/adapters/*", "contracts/apps/*", "contracts/standalones/*"]

resolver = "2"

[workspace.package]
authors = [
    "CyberHoward <cyberhoward@protonmail.com>",
    "Riada <riada@abstract.money>",
    "Abstract Money <contact@abstract.money>",
]
documentation = "https://docs.abstract.money/"
edition = "2021"
homepage = "https://abstract.money"
keywords = ["cosmos", "cosmwasm", "framework"]
license = "GPL-3.0-or-later"
repository = "https://github.com/AbstractSDK/abstract"
version = "0.26.1"

[workspace.dependencies]
## crates in order of publishing ## see docs/Publishing.md

# abstract-adapter           = { version = "0.26.1" }
abstract-adapter    = { path = "../framework/packages/abstract-adapter" }

abstract-adapter-utils         = { path = "../framework/packages/standards/utils" }
abstract-app               = { path = "../framework/packages/abstract-app" }

# Integrations
abstract-astroport-adapter   = { path = "../integrations/astroport-adapter", default-features = false }
abstract-client            = { path = "../framework/packages/abstract-client" }

## Modules
abstract-cw-staking  = { path = "./contracts/adapters/cw-staking", default-features = false }
abstract-dex-adapter = { path = "./contracts/adapters/dex", default-features = false }
abstract-dex-standard          = { path = "../framework/packages/standards/dex" }
abstract-ibc-client = { path = "../framework/contracts/native/ibc-client", default-features = false }
abstract-integration-tests = { path = "../framework/packages/abstract-integration-tests" }
abstract-interface         = { path = "../framework/packages/abstract-interface" }
abstract-macros            = { path = "../framework/packages/abstract-macros" }
# abstract-astrovault-adapter  = { path = "../integrations/astrovault-adapter", default-features = false }
# abstract-kujira-adapter      = { path = "../integrations/kujira-adapter", default-features = false }
abstract-mars-adapter        = { path = "../integrations/mars-adapter", default-features = false }
abstract-money-market-standard = { path = "../framework/packages/standards/money-market" }
abstract-neutron-dex-adapter = { path = "../integrations/neutron-dex-adapter", default-features = false }
abstract-osmosis-adapter     = { path = "../integrations/osmosis-adapter", default-features = false }
abstract-staking-standard      = { path = "../framework/packages/standards/staking" }
abstract-standalone        = { path = "../framework/packages/abstract-standalone" }
abstract-testing           = { path = "../framework/packages/abstract-testing" }
abstract-wyndex-adapter      = { path = "../integrations/wyndex-adapter", default-features = false }

## Testing
anyhow = "1"
challenge-app        = { path = "./contracts/apps/challenge", default-features = false }
chrono = { version = "0.4.31", default-features = false }
clap   = { version = "4.0.32", features = ["derive"] }

cosmwasm-schema = { git = "https://github.com/permissionlessweb/cosmwasm", branch = "zk-mvp" }
cosmwasm-std = { git = "https://github.com/permissionlessweb/cosmwasm", branch = "zk-mvp" }
croncat-app          = { path = "./contracts/apps/croncat", default-features = false }
cw-address-like = { git = "https://github.com/permissionlessweb/cw-plus-plus", branch = "zk-mvp" }
cw-asset = { git = "https://github.com/permissionlessweb/cw-asset", branch = "zk-mvp" }
cw-controllers = { git = "https://github.com/permissionlessweb/cw-minus", branch = "zk-mvp" }
cw-ica-controller = { git = "https://github.com/permissionlessweb/cw-ica-controller", branch = "zk-mvp" }
cw-orch = { git = "https://github.com/permissionlessweb/cw-orchestrator", branch = "zk-mvp" }
cw-orch-interchain = { git = "https://github.com/permissionlessweb/cw-orchestrator", branch = "zk-mvp" }
cw-orch-neutron-test-tube = { git = "https://github.com/permissionlessweb/cw-orchestrator", branch = "zk-mvp" }
cw-orch-osmosis-test-tube = { git = "https://github.com/permissionlessweb/cw-orchestrator", branch = "zk-mvp" }
cw-orch-polytone = { package = "abstract-cw-orch-polytone", git = "https://github.com/permissionlessweb/polytone", branch = "zk-mvp" }
cw-ownable = { git = "https://github.com/permissionlessweb/cw-plus-plus", branch = "zk-mvp" }
cw-plus-orch = { git = "https://github.com/permissionlessweb/cw-orchestrator", branch = "zk-mvp" }
cw-storage-plus = { git = "https://github.com/permissionlessweb/cw-storage-plus", branch = "zk-mvp" }
cw-utils = { git = "https://github.com/permissionlessweb/cw-minus", branch = "zk-mvp" }
cw2 = { git = "https://github.com/permissionlessweb/cw-minus", branch = "zk-mvp" }
cw20 = { git = "https://github.com/permissionlessweb/cw-plus", branch = "zk-mvp" }
cw20-base = { git = "https://github.com/permissionlessweb/cw-plus", branch = "zk-mvp" }
dca-app              = { path = "./contracts/apps/dca", default-features = false }

mockdex-bundle = { path = "../integrations/bundles/mockdex" }
neutron-std = { git = "https://github.com/permissionlessweb/neutron-std", branch = "zk-mvp" }
osmosis-std = { git = "https://github.com/permissionlessweb/osmosis-rust", branch = "zk-mvp" }
protobuf  = { version = "2", features = ["with-bytes"] }
rstest = "0.17.0"
schemars  = { version = "0.8.22" }
semver = "1.0"
serde     = { version = "1.0", default-features = false, features = ["derive"] }
thiserror = { version = "1.0.50" }
tokio                     = { version = "1.4", features = ["full"] }
abstract-std = { path = "../framework/packages/abstract-std" }
abstract-sdk = { path = "../framework/packages/abstract-sdk" }
cw-orch-core = { git = "https://github.com/permissionlessweb/cw-orchestrator", branch = "zk-mvp" }
cw-orch-mock = { git = "https://github.com/permissionlessweb/cw-orchestrator", branch = "zk-mvp" }
cw-orch-traits = { git = "https://github.com/permissionlessweb/cw-orchestrator", branch = "zk-mvp" }
cosmrs = { git = "https://github.com/permissionlessweb/cosmos-rust", branch = "zk-mvp" }
cosmos-sdk-proto = { git = "https://github.com/permissionlessweb/cosmos-rust", branch = "zk-mvp" }
ibc-proto = { git = "https://github.com/permissionlessweb/ibc-proto-rs", branch = "zk-mvp" }
tendermint = { git = "https://github.com/permissionlessweb/tendermint-rs", branch = "zk-mvp" }
tendermint-proto = { git = "https://github.com/permissionlessweb/tendermint-rs", branch = "zk-mvp" }
tendermint-rpc = { git = "https://github.com/permissionlessweb/tendermint-rs", branch = "zk-mvp" }
abstract-cw-multi-test = { package = "abstract-cw-multi-test", git = "https://github.com/permissionlessweb/cw-multi-test-fork", branch = "zk-mvp" }
clone-cw-multi-test = { package = "abstract-cw-multi-test", git = "https://github.com/permissionlessweb/cw-multi-test-fork", branch = "zk-mvp" }
abstract-polytone = { git = "https://github.com/permissionlessweb/polytone", branch = "zk-mvp" }
abstract-polytone-note = { git = "https://github.com/permissionlessweb/polytone", branch = "zk-mvp" }
abstract-polytone-voice = { git = "https://github.com/permissionlessweb/polytone", branch = "zk-mvp" }
abstract-polytone-proxy = { git = "https://github.com/permissionlessweb/polytone", branch = "zk-mvp" }
abstract-cw-orch-polytone = { git = "https://github.com/permissionlessweb/polytone", branch = "zk-mvp" }
osmosis-test-tube = { git = "https://github.com/permissionlessweb/osmosis-test-tube", branch = "zk-mvp" }
neutron-test-tube = { git = "https://github.com/permissionlessweb/neutron-test-tube", branch = "zk-mvp" }
simple-ica = { git = "https://github.com/permissionlessweb/cw-ibc-demo", branch = "zk-mvp" }
simple-ica-controller = { git = "https://github.com/permissionlessweb/cw-ibc-demo", branch = "zk-mvp" }
simple-ica-host = { git = "https://github.com/permissionlessweb/cw-ibc-demo", branch = "zk-mvp" }

# Backup release profile, will result in warnings during optimization
[patch.crates-io]


nam-blst = { git = "https://github.com/permissionlessweb/blst", branch = "zk-mvp" }
[profile.release]
codegen-units    = 1
debug            = false
debug-assertions = false
incremental      = false
lto              = true
opt-level        = 3
overflow-checks  = true
panic            = 'abort'
rpath            = false
