[workspace]
members = [
    "framework-clone-testing",
    "interchain-end_to_end_testing",
    "modules-clone-testing",
    "scripts",
]

# Enable the version 2 feature resolver, which avoids unifying features for targets that are not being built
#
# Critically this prevents dev-dependencies from enabling features even when not building a target that
# uses dev-dependencies, e.g. the library crate. This in turn ensures that we can catch invalid feature
# flag combinations that would otherwise only surface in dependent crates
#
# Reference - https://doc.rust-lang.org/nightly/cargo/reference/features.html#feature-resolver-version-2
# See - https://github.com/apache/arrow-rs/pull/1822/files
resolver = "2"

[workspace.package]
authors = [
    "CyberHoward <cyberhoward@protonmail.com>",
    "Riada <riada@abstract.money>",
    "Abstract Money <contact@abstract.money>",
]
documentation = "https://docs.abstract.money/"
edition = "2021"
homepage = "https://abstract.money"
keywords = ["cosmos", "cosmwasm", "framework"]
license = "GPL-3.0-or-later"
repository = "https://github.com/AbstractSDK/abstract"
version = "0.26.1"

[workspace.dependencies]
# Modules
abstract-account = { path = "../framework/contracts/account" }

# Keep these as path, creates cirular dependency otherwise
# Only need to re-publish all contracts if a re-publish of abstract-interface is required
abstract-adapter   = { path = "../framework/packages/abstract-adapter" }
abstract-app       = { path = "../framework/packages/abstract-app" }
abstract-client    = { path = "../framework/packages/abstract-client" }
# dca-app = { path = "../modules/contracts/apps/dca" }
abstract-cw-staking           = { path = "../modules/contracts/adapters/cw-staking" }
abstract-dex-adapter          = { path = "../modules/contracts/adapters/dex" }
abstract-interface = { path = "../framework/packages/abstract-interface" }
abstract-money-market-adapter = { path = "../modules/contracts/adapters/money-market" }
abstract-sdk       = { path = "../framework/packages/abstract-sdk" }
abstract-std       = { path = "../framework/packages/abstract-std" }
abstract-testing   = { path = "../framework/packages/abstract-testing" }

abstract-xion = { package = "xion-account", version = "=0.1.1", features = ["library"], path = "../../xion-account/contracts/account" }

## Testing
anyhow = "1"
# croncat-app = { path = "../modules/contracts/apps/croncat" }
challenge-app = { path = "../modules/contracts/apps/challenge" }

clap   = { version = "4.0.32", features = ["derive"] }
cosmwasm-schema = { git = "https://github.com/permissionlessweb/cosmwasm", branch = "mvp" }
cosmwasm-std = { git = "https://github.com/permissionlessweb/cosmwasm", branch = "mvp" }
cosmos-sdk-proto = { git = "https://github.com/permissionlessweb/cosmos-rust", branch = "main" }
cosmrs = { git = "https://github.com/permissionlessweb/cosmos-rust", branch = "main" }
cw-address-like = { git = "https://github.com/permissionlessweb/cw-plus-plus", branch = "main" }
cw-asset = { git = "https://github.com/permissionlessweb/cw-asset", branch = "main" }
cw-blob          = { features = ["library"], path = "../../cw-packages/contracts/cw-blob" }
cw-controllers = { git = "https://github.com/permissionlessweb/cw-minus", branch = "main" }
#polytone         = { package = "abstract-polytone", version = "2.0.0", git = "https://github.com/permissionlessweb/polytone", branch = "bump/cw3"  }
#polytone-note    = { package = "abstract-polytone-note", version = "5.0.0", git = "https://github.com/permissionlessweb/polytone", branch = "bump/cw3"  }
#cw-orch            = { version = "0.30.0", path = "../../../cw-orchestrator/cw-orch"}
#cw-orch-clone-testing = { version = "0.9.0", path = "../../../cw-orchestrator/cw-orch"}
#cw-orch-daemon        = { version = "0.29.0", path = "../../../cw-orchestrator/cw-orch"}
#cw-orch-interchain = { version = "0.8.1", path = "../../../cw-orchestrator/cw-orch"}
#cw-orch-proto         = { version = "0.9.0", path = "../../../cw-orchestrator/cw-orch"}
#cw-orch-polytone = { package = "abstract-cw-orch-polytone", version = "6.0.1", git = "https://github.com/permissionlessweb/polytone", branch = "bump/cw3"  }

cw-orch = { git = "https://github.com/permissionlessweb/cw-orchestrator", branch = "main" }
cw-orch-clone-testing   = { path = "../../cw-orchestrator/packages/clone-testing" }
cw-orch-core     = { path = "../../cw-orchestrator/packages/cw-orch-core" }
cw-orch-daemon    = { path = "../../cw-orchestrator/cw-orch-daemon" }
cw-orch-interchain = { path = "../../cw-orchestrator/cw-orch-interchain" }
cw-orch-polytone = { package = "abstract-cw-orch-polytone", git = "https://github.com/permissionlessweb/polytone", branch = "bump/cw3" }
cw-orch-proto    = { path = "../../cw-orchestrator/packages/interchain/proto" }
cw-ownable = { git = "https://github.com/permissionlessweb/cw-plus-plus", branch = "main" }
cw-storage-plus = { git = "https://github.com/permissionlessweb/cw-storage-plus", branch = "mvp" }
cw-utils = { git = "https://github.com/permissionlessweb/cw-minus", branch = "main" }
cw2 = { git = "https://github.com/permissionlessweb/cw-minus", branch = "main" }
cw20 = { git = "https://github.com/permissionlessweb/cw-plus", branch = "main" }
cw20-base = { git = "https://github.com/permissionlessweb/cw-plus", branch = "main" }
polytone = { package = "abstract-polytone", git = "https://github.com/permissionlessweb/polytone", branch = "bump/cw3" }
polytone-note = { package = "abstract-polytone-note", git = "https://github.com/permissionlessweb/polytone", branch = "bump/cw3" }
# cw20            = { version = "2.0.0" }# cw20-base       = { version = "2.0.0", features = ["library"] }

# cw-address-like = { version = "2.0" }
# cw-asset        = { version = "4.0" }
# cw-ownable      = { version = "2.0" }

abstract-macros = { path = "../framework/packages/abstract-macros" }
abstract-adapter-utils = { path = "../framework/packages/standards/utils" }
abstract-dex-standard = { path = "../framework/packages/standards/dex" }
abstract-staking-standard = { path = "../framework/packages/standards/staking" }
abstract-money-market-standard = { path = "../framework/packages/standards/money-market" }
cw-orch-mock = { path = "../../cw-orchestrator/packages/cw-orch-mock" }
cw-orch-traits = { path = "../../cw-orchestrator/packages/cw-orch-traits" }
cw-plus-orch = { git = "https://github.com/permissionlessweb/cw-orchestrator", branch = "main" }
ibc-proto = { git = "https://github.com/permissionlessweb/ibc-proto-rs", branch = "main" }
tendermint = { git = "https://github.com/permissionlessweb/tendermint-rs", branch = "main" }
tendermint-proto = { git = "https://github.com/permissionlessweb/tendermint-rs", branch = "main" }
tendermint-rpc = { git = "https://github.com/permissionlessweb/tendermint-rs", branch = "main" }
abstract-cw-multi-test = { git = "https://github.com/permissionlessweb/cw-multi-test-fork", branch = "bump/cw3/official-ibc-fork" }
clone-cw-multi-test = { git = "https://github.com/permissionlessweb/cw-multi-test-fork", branch = "cw3/adapt_for_local_execution" }
abstract-polytone-voice = { git = "https://github.com/permissionlessweb/polytone", branch = "bump/cw3" }
abstract-polytone-proxy = { git = "https://github.com/permissionlessweb/polytone", branch = "bump/cw3" }
osmosis-std = { git = "https://github.com/permissionlessweb/osmosis-rust", branch = "main" }
osmosis-test-tube = { git = "https://github.com/permissionlessweb/osmosis-test-tube", branch = "main" }
neutron-std = { git = "https://github.com/permissionlessweb/neutron-std", branch = "feat/cw3" }
neutron-test-tube = { git = "https://github.com/permissionlessweb/neutron-test-tube", branch = "main" }
simple-ica = { git = "https://github.com/permissionlessweb/cw-ibc-demo", branch = "cosmwasm3" }
simple-ica-controller = { git = "https://github.com/permissionlessweb/cw-ibc-demo", branch = "cosmwasm3" }
simple-ica-host = { git = "https://github.com/permissionlessweb/cw-ibc-demo", branch = "cosmwasm3" }

protobuf  = { version = "2", features = ["with-bytes"] }
rstest = "0.17.0"
schemars  = { version = "0.8.22" }
semver = "1.0"
serde     = { version = "1.0", default-features = false, features = ["derive"] }
thiserror = { version = "1.0.49" }
tokio  = { version = "1.33.0", features = ["full"] }

# Backup release profile, will result in warnings during optimization
[patch.crates-io]
nam-blst = { path = "../../nam-blst/bindings/rust" }

# Fork patches (managed by dep-switch.py)
cosmwasm-vm = { git = "https://github.com/permissionlessweb/cosmwasm", branch = "mvp" }
[profile.release]
codegen-units    = 1
debug            = false
debug-assertions = false
incremental      = false
lto              = true
opt-level        = 3
overflow-checks  = true
panic            = 'abort'
rpath            = false
