[workspace]
members = [
    "framework-clone-testing",
    "interchain-end_to_end_testing",
    "modules-clone-testing",
    "scripts",
]

# Enable the version 2 feature resolver, which avoids unifying features for targets that are not being built
#
# Critically this prevents dev-dependencies from enabling features even when not building a target that
# uses dev-dependencies, e.g. the library crate. This in turn ensures that we can catch invalid feature
# flag combinations that would otherwise only surface in dependent crates
#
# Reference - https://doc.rust-lang.org/nightly/cargo/reference/features.html#feature-resolver-version-2
# See - https://github.com/apache/arrow-rs/pull/1822/files
resolver = "2"

[workspace.package]
authors = [
    "CyberHoward <cyberhoward@protonmail.com>",
    "Riada <riada@abstract.money>",
    "Abstract Money <contact@abstract.money>",
]
documentation = "https://docs.abstract.money/"
edition = "2021"
homepage = "https://abstract.money"
keywords = ["cosmos", "cosmwasm", "framework"]
license = "GPL-3.0-or-later"
repository = "https://github.com/AbstractSDK/abstract"
version = "0.26.1"

[workspace.dependencies]
# Modules
abstract-account = { path = "../framework/contracts/account" }

# Keep these as path, creates cirular dependency otherwise
# Only need to re-publish all contracts if a re-publish of abstract-interface is required
abstract-adapter   = { path = "../framework/packages/abstract-adapter" }
abstract-app       = { path = "../framework/packages/abstract-app" }
abstract-client    = { path = "../framework/packages/abstract-client" }
# dca-app = { path = "../modules/contracts/apps/dca" }
abstract-cw-staking           = { path = "../modules/contracts/adapters/cw-staking" }
abstract-dex-adapter          = { path = "../modules/contracts/adapters/dex" }
abstract-interface = { path = "../framework/packages/abstract-interface" }
abstract-money-market-adapter = { path = "../modules/contracts/adapters/money-market" }
abstract-sdk       = { path = "../framework/packages/abstract-sdk" }
abstract-std       = { path = "../framework/packages/abstract-std" }
abstract-testing   = { path = "../framework/packages/abstract-testing" }

abstract-xion = { package = "xion-account", version = "=0.1.1", features = ["library"], path = "../../xion-account/contracts/account" }

## Testing
anyhow = "1"
# croncat-app = { path = "../modules/contracts/apps/croncat" }
challenge-app = { path = "../modules/contracts/apps/challenge" }

clap   = { version = "4.0.32", features = ["derive"] }
cosmwasm-schema = { version = "3.0.4" }
cosmwasm-std    = { version = "3.0.4" }
cosmos-sdk-proto = { path = "../../cosmos-rust/cosmos-sdk-proto" }
cosmrs           = { path = "../../cosmos-rust/cosmrs" }
cw-address-like = { path = "../../cw-plus-plus/packages/address-like" }
cw-asset        = { path = "../../cw-asset" }
cw-blob          = { features = ["library"], path = "../../cw-packages/contracts/cw-blob" }
cw-controllers  = { path = "../../cw-minus/packages/controllers" }
#polytone         = { package = "abstract-polytone", version = "2.0.0", git = "https://github.com/permissionlessweb/polytone", branch = "bump/cw3"  }
#polytone-note    = { package = "abstract-polytone-note", version = "5.0.0", git = "https://github.com/permissionlessweb/polytone", branch = "bump/cw3"  }
#cw-orch            = { version = "0.30.0", path = "../../../cw-orchestrator/cw-orch"}
#cw-orch-clone-testing = { version = "0.9.0", path = "../../../cw-orchestrator/cw-orch"}
#cw-orch-daemon        = { version = "0.29.0", path = "../../../cw-orchestrator/cw-orch"}
#cw-orch-interchain = { version = "0.8.1", path = "../../../cw-orchestrator/cw-orch"}
#cw-orch-proto         = { version = "0.9.0", path = "../../../cw-orchestrator/cw-orch"}
#cw-orch-polytone = { package = "abstract-cw-orch-polytone", version = "6.0.1", git = "https://github.com/permissionlessweb/polytone", branch = "bump/cw3"  }

cw-orch            = { path = "../../cw-orchestrator/cw-orch" }
cw-orch-clone-testing   = { path = "../../cw-orchestrator/packages/clone-testing" }
cw-orch-core     = { path = "../../cw-orchestrator/packages/cw-orch-core" }
cw-orch-daemon    = { path = "../../cw-orchestrator/cw-orch-daemon" }
cw-orch-interchain = { path = "../../cw-orchestrator/cw-orch-interchain" }
cw-orch-polytone = { package = "abstract-cw-orch-polytone", path = "../../polytone/packages/cw-orch-polytone" }
cw-orch-proto    = { path = "../../cw-orchestrator/packages/interchain/proto" }
cw-ownable      = { path = "../../cw-plus-plus/packages/ownable" }
cw-storage-plus = "3.0.1"
cw-utils        = { path = "../../cw-minus/packages/cw-utils" }
cw2             = { path = "../../cw-minus/packages/cw2" }
cw20            = { path = "../../cw-plus/packages/cw20" }
cw20-base       = { path = "../../cw-plus/contracts/cw20-base" }
polytone         = { package = "abstract-polytone", path = "../../polytone/packages/polytone" }
polytone-note    = { package = "abstract-polytone-note", path = "../../polytone/contracts/main/note" }
# cw20            = { version = "2.0.0" }# cw20-base       = { version = "2.0.0", features = ["library"] }

# cw-address-like = { version = "2.0" }
# cw-asset        = { version = "4.0" }
# cw-ownable      = { version = "2.0" }

abstract-macros = { path = "../framework/packages/abstract-macros" }
abstract-adapter-utils = { path = "../framework/packages/standards/utils" }
abstract-dex-standard = { path = "../framework/packages/standards/dex" }
abstract-staking-standard = { path = "../framework/packages/standards/staking" }
abstract-money-market-standard = { path = "../framework/packages/standards/money-market" }
cw-orch-mock = { path = "../../cw-orchestrator/packages/cw-orch-mock" }
cw-orch-traits = { path = "../../cw-orchestrator/packages/cw-orch-traits" }
cw-plus-orch = { path = "../../cw-orchestrator/packages/integrations/cw-plus" }
ibc-proto = { path = "../../ibc-proto-rs" }
tendermint = { path = "../../tendermint-rs/tendermint" }
tendermint-proto = { path = "../../tendermint-rs/proto" }
tendermint-rpc = { path = "../../tendermint-rs/rpc" }
abstract-cw-multi-test = { path = "../../cw-multi-test-fork" }
clone-cw-multi-test = { path = "../../clone-cw-multi-test" }
abstract-polytone-voice = { path = "../../polytone/contracts/main/voice" }
abstract-polytone-proxy = { path = "../../polytone/contracts/main/proxy" }
osmosis-std = { path = "../../osmosis-rust/packages/osmosis-std" }
osmosis-test-tube = { path = "../../osmosis-test-tube/packages/osmosis-test-tube" }
neutron-std = { path = "../../neutron-std/packages/neutron-std" }
neutron-test-tube = { path = "../../neutron-test-tube/packages/neutron-test-tube" }
simple-ica = { path = "../../cw-ibc-demo/packages/simple-ica" }
simple-ica-controller = { path = "../../cw-ibc-demo/contracts/simple-ica-controller" }
simple-ica-host = { path = "../../cw-ibc-demo/contracts/simple-ica-host" }

protobuf  = { version = "2", features = ["with-bytes"] }
rstest = "0.17.0"
schemars  = { version = "0.8.22" }
semver = "1.0"
serde     = { version = "1.0", default-features = false, features = ["derive"] }
thiserror = { version = "1.0.49" }
tokio  = { version = "1.33.0", features = ["full"] }

# Backup release profile, will result in warnings during optimization
[patch.crates-io]
nam-blst = { path = "../../nam-blst/bindings/rust" }
cosmwasm-vm = { path = "../../cosmwasm/packages/vm" }

[profile.release]
codegen-units    = 1
debug            = false
debug-assertions = false
incremental      = false
lto              = true
opt-level        = 3
overflow-checks  = true
panic            = 'abort'
rpath            = false
