[package]
authors     = { workspace = true }
description = "Abstract IBC Client Contract"
edition     = { workspace = true }
license     = { workspace = true }
name        = "abstract-ibc-client"
readme      = "README.md"
repository  = "https://github.com/AbstractSDK/abstract"
version     = { workspace = true }

[lib]
crate-type = ["cdylib", "rlib"]

[features]
default = ["export"]
export  = []

[dependencies]
abstract-macros = { workspace = true }
abstract-sdk    = { workspace = true }
abstract-std    = { workspace = true }
anybuf          = { workspace = true }
cosmwasm-std    = { workspace = true, features = ["stargate", "staking"] }
cw-ownable      = { workspace = true }
cw-paginate = { git = "https://github.com/permissionlessweb/cw-plus-plus", branch = "zk-mvp" }
cw-storage-plus = { workspace = true }
cw-utils        = { workspace = true }
cw2             = { workspace = true }
semver          = { workspace = true }

thiserror = { workspace = true }

[dev-dependencies]
abstract-interface = { workspace = true, features = ["interchain", "testing"] }
abstract-testing   = { workspace = true }
cosmwasm-schema    = { workspace = true }

coverage-helper = { workspace = true }
cw-orch = { workspace = true }
cw-orch-interchain = { workspace = true }
ibc-proto       = { workspace = true }
prost           = { version = "0.14.3", default-features = false }

[lints]
workspace = true

[profile.release]
overflow-checks = true
