[package]
authors     = { workspace = true }
description = "Abstract Interchain Account (ICA) Types"
edition     = { workspace = true }
license     = { workspace = true }
name        = "abstract-ica"
readme      = "README.md"
repository  = "https://github.com/AbstractSDK/abstract"
version     = { workspace = true }


[features]
# for quicker tests, cargo test --lib

[dependencies]
cosmwasm-schema = { workspace = true }
cosmwasm-std    = { workspace = true, features = ["iterator"] }
cw-ownable      = { workspace = true }
map-macro       = "0.3.0"

abstract-sdk = { workspace = true }
cw-orch      = { workspace = true }

# EVM
polytone-evm = { version = "2.0.0",git = "https://github.com/permissionlessweb/polytone", branch = "bump/cw3-evm"  }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
workspace-hack = { version = "0.1", path = "../../workspace-hack" }

[dev-dependencies]
abstract-testing = { path = "../abstract-testing" }
anyhow           = { workspace = true }
coverage-helper  = { workspace = true }
cw20-base        = { workspace = true }
rstest           = { workspace = true }
