[package]
authors     = { workspace = true }
description = "Abstract ICA Client Contract"
edition     = { workspace = true }
license     = { workspace = true }
name        = "abstract-ica-client"
readme      = "README.md"
repository  = "https://github.com/AbstractSDK/abstract"
version     = { workspace = true }

[lib]
crate-type = ["cdylib", "rlib"]

[features]
default = ["export"]
export  = []

[dependencies]
abstract-ica    = { workspace = true }
abstract-macros = { workspace = true }
abstract-sdk    = { workspace = true }
abstract-std    = { workspace = true }
cosmwasm-schema = { workspace = true }
cosmwasm-std    = { workspace = true, features = ["stargate", "staking"] }
cw-ownable      = { workspace = true }
cw2             = { workspace = true }

evm-note = { path = "../../../../../polytone-evm/contracts/main/evm-note", features = ["library"] }
polytone-evm = { path = "../../../../../polytone-evm/packages/polytone-evm" }
semver          = { workspace = true }
thiserror       = { workspace = true }

[dev-dependencies]
abstract-testing = { workspace = true }
cosmwasm-schema  = { workspace = true }
coverage-helper  = { workspace = true }

[lints]
workspace = true

[profile.release]
overflow-checks = true
