[package]
authors     = { workspace = true }
description = "Abstract Tendermint Staking Adapter. This contract allows interacting with staking on multiple Tendermint chains"
edition     = { workspace = true }
license     = { workspace = true }
name        = "abstract-tendermint-staking-adapter"
version     = { workspace = true }

exclude = ["contract.wasm", "hash.txt"]

[lib]
crate-type = ["cdylib", "rlib"]

[features]
default = ["export"]
export  = []
schema  = ["abstract-adapter/schema"]

# Keep as is until TendermintStake updates.
[dependencies]
abstract-adapter = { workspace = true }
cosmwasm-schema  = { workspace = true }
cosmwasm-std     = { workspace = true }

cw-orch = { workspace = true }
schemars         = { workspace = true }
thiserror        = { workspace = true }

[dev-dependencies]
abstract-adapter = { workspace = true, features = ["schema"] }

[[example]]
name              = "schema"
required-features = ["schema"]
